# 网络配置
networks:
  safeline-ce:
    # 设置网络名称
    name: safeline-ce
    # 设置网络驱动为桥接
    driver: bridge
    # 配置 IP 地址管理
    ipam:
      driver: default
      config:
          # 设置网关
        - gateway: ${SUBNET_PREFIX:?SUBNET_PREFIX required}.1
          # 设置网段
          subnet: ${SUBNET_PREFIX}.0/24
    # 设置网络驱动选项
    driver_opts:
      com.docker.network.bridge.name: safeline-ce

services:
  postgres:
    # 设置镜像
    image: ${IMAGE_PREFIX}/safeline-postgres${ARCH_SUFFIX}:15.2
    # 设置容器名
    container_name: safeline-pg
    # 设置容器退出时总是重启
    restart: always
    
    # 设置环境变量
    environment:
      - POSTGRES_USER=safeline-ce
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?postgres password required}
    
    # 配置数据卷目录
    volumes:
      - ${SAFELINE_DIR}/resources/postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    
    # 设置启动命令
    command: [postgres, -c, max_connections=600]
    
    # 健康检查
    healthcheck:
      test: pg_isready -U safeline-ce -d safeline-ce
    
    # 配置日志文件，防止日志过多占用大量磁盘空间
    logging:
      driver: json-file
      options:
        # 配置单日志文件最大大小
        max-size: ${POSTGRES_MAX_LOG_SIZE}${POSTGRES_MAX_LOG_SIZE_UNIT}
        # 最多保留多少个日志文件
        max-file: ${POSTGRES_MAXNUMBER_LOG}
    
    networks:
      safeline-ce:
        # 配置容器 IP
        ipv4_address: ${SUBNET_PREFIX}.2

  mgt:
    # 设置镜像
    image: ${IMAGE_PREFIX}/safeline-mgt${REGION}${ARCH_SUFFIX}:${IMAGE_TAG:?image tag required}
    # 设置容器名
    container_name: safeline-mgt
    # 设置容器退出时总是重启
    restart: always
    
    # 设置端口转发
    ports:
      - ${MGT_PORT:-9443}:1443
    
    # 设置环境变量
    environment:
      - MGT_PG=postgres://safeline-ce:${POSTGRES_PASSWORD}@safeline-pg/safeline-ce?sslmode=disable
      - MGT_PROXY=${MGT_PROXY}
    
    # 配置数据卷目录
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SAFELINE_DIR}/resources/mgt:/app/data
      - ${SAFELINE_DIR}/logs/nginx:/app/log/nginx:z
      - ${SAFELINE_DIR}/resources/sock:/app/sock
      - /var/run:/app/run
    
    # 健康检查
    healthcheck:
      test: curl -k -f https://localhost:1443/api/open/health
    
    # 设置依赖服务
    depends_on:
      - postgres
      - fvm
    
    # 配置日志文件，防止日志过多占用大量磁盘空间
    logging:
      driver: json-file
      options:
        # 配置单日志文件最大大小
        max-size: ${MGT_MAX_LOG_SIZE}${MGT_MAX_LOG_SIZE_UNIT}
        # 最多保留多少个日志文件
        max-file: ${MGT_MAXNUMBER_LOG}
    
    networks:
      safeline-ce:
        # 配置容器 IP
        ipv4_address: ${SUBNET_PREFIX}.4

  detect:
    # 设置镜像
    image: ${IMAGE_PREFIX}/safeline-detector${REGION}${ARCH_SUFFIX}:${IMAGE_TAG}
    # 设置容器名
    container_name: safeline-detector
    # 设置容器退出时总是重启
    restart: always
    
    # 设置环境变量
    environment:
      - LOG_DIR=/logs/detector
    
    # 配置数据卷目录
    volumes:
      - ${SAFELINE_DIR}/resources/detector:/resources/detector
      - ${SAFELINE_DIR}/logs/detector:/logs/detector
      - /etc/localtime:/etc/localtime:ro
    
    # 配置日志文件，防止日志过多占用大量磁盘空间
    logging:
      driver: json-file
      options:
        # 配置单日志文件最大大小
        max-size: ${DETECT_MAX_LOG_SIZE}${DETECT_MAX_LOG_SIZE_UNIT}
        # 最多保留多少个日志文件
        max-file: ${DETECT_MAXNUMBER_LOG}
    
    networks:
      safeline-ce:
        # 配置容器 IP
        ipv4_address: ${SUBNET_PREFIX}.5

  tengine:
    # 设置镜像
    image: ${IMAGE_PREFIX}/safeline-tengine${REGION}${ARCH_SUFFIX}:${IMAGE_TAG}
    # 设置容器名
    container_name: safeline-tengine
    # 设置容器退出时总是重启
    restart: always
    
    # 设置环境变量
    environment:
      - TCD_MGT_API=https://${SUBNET_PREFIX}.4:1443/api/open/publish/server
      - TCD_SNSERVER=${SUBNET_PREFIX}.5:8000
      # deprecated
      - SNSERVER_ADDR=${SUBNET_PREFIX}.5:8000
      - CHAOS_ADDR=${SUBNET_PREFIX}.10
    
    # 配置数据卷目录
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - ${SAFELINE_DIR}/resources/nginx:/etc/nginx
      - ${SAFELINE_DIR}/resources/detector:/resources/detector
      - ${SAFELINE_DIR}/resources/chaos:/resources/chaos
      - ${SAFELINE_DIR}/logs/nginx:/var/log/nginx:z
      - ${SAFELINE_DIR}/resources/cache:/usr/local/nginx/cache
      - ${SAFELINE_DIR}/resources/sock:/app/sock
    
    # 设置文件描述符限制
    ulimits:
      nofile: 131072
    
    # 配置日志文件，防止日志过多占用大量磁盘空间
    logging:
      driver: json-file
      options:
        # 配置单日志文件最大大小
        max-size: ${TENGINE_MAX_LOG_SIZE}${TENGINE_MAX_LOG_SIZE_UNIT}
        # 最多保留多少个日志文件
        max-file: ${TENGINE_MAXNUMBER_LOG}
    
    # 使用主机网络模式
    network_mode: host

  luigi:
    # 设置镜像
    image: ${IMAGE_PREFIX}/safeline-luigi${REGION}${ARCH_SUFFIX}:${IMAGE_TAG}
    # 设置容器名
    container_name: safeline-luigi
    # 设置容器退出时总是重启
    restart: always
    
    # 设置环境变量
    environment:
      - MGT_IP=${SUBNET_PREFIX}.4
      - LUIGI_PG=postgres://safeline-ce:${POSTGRES_PASSWORD}@safeline-pg/safeline-ce?sslmode=disable
    
    # 配置数据卷目录
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SAFELINE_DIR}/resources/luigi:/app/data
    
    # 设置依赖服务
    depends_on:
      - detect
      - mgt
    
    # 配置日志文件，防止日志过多占用大量磁盘空间
    logging:
      driver: json-file
      options:
        # 配置单日志文件最大大小
        max-size: ${LUIGI_MAX_LOG_SIZE}${LUIGI_MAX_LOG_SIZE_UNIT}
        # 最多保留多少个日志文件
        max-file: ${LUIGI_MAXNUMBER_LOG}
    
    networks:
      safeline-ce:
        # 配置容器 IP
        ipv4_address: ${SUBNET_PREFIX}.7

  fvm:
    # 设置镜像
    image: ${IMAGE_PREFIX}/safeline-fvm${REGION}${ARCH_SUFFIX}:${IMAGE_TAG}
    # 设置容器名
    container_name: safeline-fvm
    # 设置容器退出时总是重启
    restart: always
    
    # 配置数据卷目录
    volumes:
      - /etc/localtime:/etc/localtime:ro
    
    # 配置日志文件，防止日志过多占用大量磁盘空间
    logging:
      driver: json-file
      options:
        # 配置单日志文件最大大小
        max-size: ${FVM_MAX_LOG_SIZE}${FVM_MAX_LOG_SIZE_UNIT}
        # 最多保留多少个日志文件
        max-file: ${FVM_MAXNUMBER_LOG}
    
    networks:
      safeline-ce:
        # 配置容器 IP
        ipv4_address: ${SUBNET_PREFIX}.8

  chaos:
    # 设置镜像
    image: ${IMAGE_PREFIX}/safeline-chaos${REGION}${ARCH_SUFFIX}:${IMAGE_TAG}
    # 设置容器名
    container_name: safeline-chaos
    # 设置容器退出时总是重启
    restart: always
    
    # 设置环境变量
    environment:
      - DB_ADDR=postgres://safeline-ce:${POSTGRES_PASSWORD}@safeline-pg/safeline-ce?sslmode=disable
    
    # 配置数据卷目录
    volumes:
      - ${SAFELINE_DIR}/resources/sock:/app/sock
      - ${SAFELINE_DIR}/resources/chaos:/app/chaos
    
    # 配置日志文件，防止日志过多占用大量磁盘空间
    logging:
      driver: json-file
      options:
        # 配置单日志文件最大大小
        max-size: ${CHAOS_MAX_LOG_SIZE}${CHAOS_MAX_LOG_SIZE_UNIT}
        # 最多保留多少个日志文件
        max-file: ${CHAOS_MAXNUMBER_LOG}
    
    networks:
      safeline-ce:
        # 配置容器 IP
        ipv4_address: ${SUBNET_PREFIX}.10