# 网络配置
networks:
  twikoo:
    # 设置网络名称
    name: twikoo
    # 设置网络驱动为桥接
    driver: bridge
    # 配置 IP 地址管理
    ipam:
      driver: default
      config:
          # 设置网关
        - gateway: ${SUBNET_PREFIX:?SUBNET_PREFIX required}.1
          # 设置网段
          subnet: ${SUBNET_PREFIX}.0/24
    # 设置网络驱动选项
    driver_opts:
      com.docker.network.bridge.name: twikoo

services:
  twikoo:
    # 设置镜像
    image: imaegoo/twikoo
    # 设置容器名
    container_name: twikoo
    # 设置容器退出时总是重启
    restart: unless-stopped
    
    # 设置端口转发
    # 若你使用反向代理只需要反代容器ip：8080，不需要端口转发（注释port配置的所有内容），可增加安全性
    ports:
      - ${WEB_HTTP_PORT:?web http port required}:8080
    
    # 设置环境变量
    environment:
      TWIKOO_THROTTLE: 1000
      # 设置时区为 Asia/Shanghai
      TZ: Asia/Shanghai
    
    # 配置数据卷目录
    volumes:
      - ${DATA_PATH:?data path required}/data:/app/data
    
    # 配置日志文件，防止日志过多占用大量磁盘空间
    logging:
      driver: json-file
        # 日志切割配置
      options:
        # 配置单日志文件最大大小
        max-size: ${MAX_LOG_SIZE}${MAX_LOG_SIZE_UNIT}
        # 最多保留多少个日志文件
        max-file: ${MAXNUMBER_LOG}
    
    networks:
      twikoo:
        # 配置容器 IP
        ipv4_address: ${SUBNET_PREFIX}.2